### PR TITLE
Translation split into partial class system.

### LINKED ISSUE #19: Translation class should be converted to a partial class.

### PR DESCRIPTION
**Pull request by CollinMcKinney**

### CODE REVIEW

**Comment by CollinMcKinney** [comment]
Translation.cs has become Translation.Designer.cs, with partial classes for each language (currently Translation.English.cs, Translation.German.cs, and Translation.Spanish.cs)

**Review by CollinMcKinney — COMMENTED** [review]
Theres a formatting (whitespace) error, ignore that as it does not affect compilation. Will look into auto formatting rules at some point.

**Comment by RyadaProductions** [comment]
Looks good on first glance. Although I would personally rename Translation.Designer.cs to Translation.cs
Designer.cs is generally used for auto generated files from visual studio that have a visual designer, so to me it doesn’t make sense that it’s on a code only file.

**Comment by CollinMcKinney** [comment]
My thought with the .Designer.cs naming was that since it is the base implementation of a partial class, it should receive that name. But now I think you're right that it should have the .Designer dropped from the name for clarity purposes.

**Review by CollinMcKinney — COMMENTED** [review]
Translation.Designer.cs has been (re)renamed to Translation.cs with latest commit.

**Review by CollinMcKinney — COMMENTED** [review]
Going to go ahead and merge it and delete the cleanup branch.

A new "electron" branch was created where the project will be rewritten using ElectronNET.

Imagery and core source-code has been copied over; more language support could be added to Translation for now, but most of the other code should be considered stale, and no need for further cleanup.

**Comment by RyadaProductions** [comment]
Was unable to have jnternet today after I send my initial suggestion but it looks good to me now. :) so no complaints about the merge.

I’ll have a look at the electron branch tomorrow

**Pull request merged**
